# Site settings
title: Bo Hua
email: 
description: > # this means to ignore newlines until "baseurl:"
  Bo Hua's under-construction website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  bo-hua

# Build settings
markdown: kramdown
